-- Remote recovery/audit tables.
-- sync_outbox intentionally remains local-only because it is a client retry queue.

create table if not exists public.entity_versions (
    entity_type text not null,
    entity_id bigint not null,
    local_version integer not null default 0,
    remote_version integer not null default 0,
    updated_at timestamp with time zone default now(),
    synced_at timestamp with time zone,
    primary key (entity_type, entity_id)
);

create table if not exists public.semantic_undo_log (
    id bigint generated by default as identity primary key,
    transaction_id text not null,
    operation_id bigint,
    action_type text not null,
    entity_type text not null,
    entity_id bigint,
    before_snapshot text,
    after_snapshot text,
    status text not null default 'active',
    created_at timestamp with time zone default now(),
    undone_at timestamp with time zone,
    undo_error text,
    operation_type text,
    inverse_action_type text,
    inverse_payload text
);

create index if not exists idx_semantic_undo_log_transaction
    on public.semantic_undo_log(transaction_id);

create index if not exists idx_semantic_undo_log_operation
    on public.semantic_undo_log(operation_id);

create index if not exists idx_semantic_undo_log_status
    on public.semantic_undo_log(status);

create index if not exists idx_semantic_undo_log_entity
    on public.semantic_undo_log(entity_type, entity_id);
