-- Season management schema.

create table if not exists public.stagioni (
    id bigint generated by default as identity primary key,
    codice text not null unique,
    anno_inizio integer not null,
    anno_fine integer not null,
    data_inizio date not null,
    data_fine date,
    stato text not null default 'attiva',
    fase_corrente text,
    storage_path text not null,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    deleted boolean not null default false
);

create table if not exists public.stagione_fasi (
    id bigint generated by default as identity primary key,
    stagione_id bigint not null references public.stagioni(id) on delete cascade,
    codice_fase text not null,
    nome text not null,
    data_inizio date,
    data_fine date,
    stato text not null default 'pianificata',
    asta_data_inizio date,
    asta_data_fine date,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    unique (stagione_id, codice_fase)
);

create table if not exists public.stagione_files (
    id bigint generated by default as identity primary key,
    stagione_id bigint not null references public.stagioni(id) on delete cascade,
    fase_id bigint references public.stagione_fasi(id) on delete set null,
    tipo_file text not null,
    nome_logico text not null,
    path text not null,
    created_at timestamp with time zone default now(),
    note text
);

create table if not exists public.stagione_step_log (
    id bigint generated by default as identity primary key,
    stagione_id bigint not null references public.stagioni(id) on delete cascade,
    fase_id bigint references public.stagione_fasi(id) on delete set null,
    step_key text not null,
    status text not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    error_message text,
    metadata_json text
);

create unique index if not exists ux_stagioni_single_active
    on public.stagioni(stato)
    where stato = 'attiva' and deleted = false;

create index if not exists idx_stagione_fasi_stagione_id
    on public.stagione_fasi(stagione_id);

create index if not exists idx_stagione_files_stagione_id
    on public.stagione_files(stagione_id);

create index if not exists idx_stagione_files_fase_id
    on public.stagione_files(fase_id);

create index if not exists idx_stagione_step_log_stagione_id
    on public.stagione_step_log(stagione_id);

create index if not exists idx_stagione_step_log_fase_id
    on public.stagione_step_log(fase_id);
