-- Initial Supabase/Postgres schema for Fantamanager.
-- Mirrors the current SQLite model while adding relational constraints.

create table if not exists public.fantasquadre (
    id bigint generated by default as identity primary key,
    nome text not null,
    fm integer not null,
    campionati integer not null default 0,
    coppe integer not null default 0,
    supercoppe integer not null default 0,
    deleted boolean not null default false
);

create table if not exists public.giocatori (
    id bigint generated by default as identity primary key,
    nome text not null,
    squadra text,
    fantasquadra_id bigint references public.fantasquadre(id),
    spesa integer,
    data_acquisto date,
    fascia text,
    quotazione integer,
    dq integer,
    valore_svincolo integer,
    scadenza_contratto date,
    in_prestito_a text,
    prestito_a_fantasquadra_id bigint references public.fantasquadre(id),
    inizio_prestito date,
    fine_prestito date,
    convocato boolean not null default true,
    in_serie_a boolean not null default true,
    deleted boolean not null default false
);

create table if not exists public.operazioni (
    id bigint generated by default as identity primary key,
    fantasquadra_a_id bigint not null references public.fantasquadre(id),
    fantasquadra_b_id bigint references public.fantasquadre(id),
    tipo_operazione text not null,
    conguaglio integer not null default 0,
    conguaglio_da_id bigint references public.fantasquadre(id),
    data date,
    clausole text,
    operation_snapshot text
);

create table if not exists public.operazione_giocatori (
    operazione_id bigint not null references public.operazioni(id) on delete cascade,
    giocatore_id bigint not null references public.giocatori(id) on delete cascade,
    primary key (operazione_id, giocatore_id)
);

create table if not exists public.entity_versions (
    entity_type text not null,
    entity_id bigint not null,
    local_version integer not null default 0,
    remote_version integer not null default 0,
    updated_at timestamp with time zone default now(),
    synced_at timestamp with time zone,
    primary key (entity_type, entity_id)
);

create table if not exists public.semantic_undo_log (
    id bigint generated by default as identity primary key,
    transaction_id text not null,
    operation_id bigint,
    action_type text not null,
    entity_type text not null,
    entity_id bigint,
    before_snapshot text,
    after_snapshot text,
    status text not null default 'active',
    created_at timestamp with time zone default now(),
    undone_at timestamp with time zone,
    undo_error text,
    operation_type text,
    inverse_action_type text,
    inverse_payload text
);

create index if not exists idx_fantasquadre_deleted
    on public.fantasquadre(deleted);

create index if not exists idx_giocatori_squadra
    on public.giocatori(squadra);

create index if not exists idx_giocatori_fantasquadra_id
    on public.giocatori(fantasquadra_id);

create index if not exists idx_giocatori_in_prestito_a
    on public.giocatori(in_prestito_a);

create index if not exists idx_giocatori_prestito_a_fantasquadra_id
    on public.giocatori(prestito_a_fantasquadra_id);

create index if not exists idx_giocatori_deleted
    on public.giocatori(deleted);

create index if not exists idx_operazioni_fantasquadra_a_id
    on public.operazioni(fantasquadra_a_id);

create index if not exists idx_operazioni_fantasquadra_b_id
    on public.operazioni(fantasquadra_b_id);

create index if not exists idx_operazioni_conguaglio_da_id
    on public.operazioni(conguaglio_da_id);

create index if not exists idx_operazioni_tipo_operazione
    on public.operazioni(tipo_operazione);

create index if not exists idx_operazioni_data
    on public.operazioni(data);

create index if not exists idx_semantic_undo_log_transaction
    on public.semantic_undo_log(transaction_id);

create index if not exists idx_semantic_undo_log_operation
    on public.semantic_undo_log(operation_id);

create index if not exists idx_semantic_undo_log_status
    on public.semantic_undo_log(status);

create index if not exists idx_semantic_undo_log_entity
    on public.semantic_undo_log(entity_type, entity_id);
